name = "a0b_atsam3x8e_gpio"
description = "A0B ATSAM3X8E GPIO/EXTI"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "atsam3x8e", "gpio", "arduino", "due"]

project-files = ["gnat/a0b_atsam3x8e_gpio.gpr"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_gpio = "*"
a0b_exti = "*"
a0b_svd_atsam3x8e = "*"
