name = "a0b_atsam3x8e_gpio"
description = "A0B ATSAM3X8E GPIO/EXTI"
version = "0.1.0"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded", "gpio", "atsam3x8e", "sam3x8e", "arduino", "due"]

project-files = ["gnat/a0b_atsam3x8e_gpio.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_gpio = "*"
a0b_exti = "*"
a0b_atsam3x8e = "*"

[[actions]]
type = "test"
directory = "selftest"
command = ["alr", "build"]
